try:
    from configLoader import convertToConfigData
    from configLoader import configSave
    from configLoader import configLoad
    configLoad()
    from configLoader import titleScreenWaitTime, decorType, useANSI, configVersion, programVersion
except Exception as e:
    print(e)
    print("Critical Error: config loader not found")
    exit(1)

try:
    import colorscheme
    colorScheme=colorscheme.defineColors(useANSI)
except Exception as e:
    print(e)
    colorScheme={
        "default":"",
        "bold":"",
        "error":"",
        "warning":"",
        "success":"",
        "link":"",
        "null":"",
        "typeerror":"",
        "command":"",
        "subcommand":"",
        "section":"",
        "id":"",
        "value":"",
        "typeinvalid":""
    }

date="27 Feb 2026"

versionNames=[0,"0.9","0.10 Beta"]

str={
    "err_line":" occured on line ",
    "err_mod_curses":colorScheme["error"]+"No Curses module installed."+colorScheme["default"]+" You will be unable to use "+colorScheme["command"]+"settings"+colorScheme["default"]+" and "+colorScheme["command"]+"replace"+colorScheme["default"]+" commands, as they use a Curses GUI.\nPlease install it using the "+colorScheme["bold"]+"pip install curses"+colorScheme["default"]+" command.",
    "err_mod_keyboard":colorScheme["error"]+"No Keyboard module installed. You will be unable to type."+colorScheme["default"]+"\nPlease install it using the "+colorScheme["bold"]+"pip install keyboard"+colorScheme["default"]+" command.",
    "err_mod_win32gui":colorScheme["error"]+"No Win32GUI module installed."+colorScheme["default"]+" The console window will be unable to know if it is highlighted.\nPlease install it using the "+colorScheme["bold"]+"pip install win32gui"+colorScheme["default"]+" command.",
    "err_conf_load":"Configuration file may be invalid.",
    "err_curses_load":colorScheme["error"]+"Current console environment does not support Curses."+colorScheme["default"],
    "err_file_unicode":colorScheme["error"]+"Invalid file!\nConsider converting your level data to txt or csv."+colorScheme["default"],
    "err_parse_no_delimiters":colorScheme["error"]+"Invalid level code!\nNo valid delimiters found in file."+colorScheme["default"],
    "err_parse_unterminated":colorScheme["error"]+"Invalid or incomplete level code\n",
    "err_parse_tile_id":colorScheme["error"]+"Invalid tile data\n",
    "err_parse_gen":colorScheme["error"]+"exception encountered during parsing\ndata dump:\n",
    "err_color_load":"File \"colorscheme.py\" is missing. No colors will be displayed.",
    "err_con_size_1":"Console size could not be obtained.",
    "err_con_size_2":"The default size of 80x25 characters has been set.",
    "err_con_size_3":"Please manually adjust your console's window size to the size of this box.",
    "err_con_size_4":"Press Enter when done.",
    "te_comm":colorScheme["typeerror"]+"Invalid Command!"+colorScheme["default"],
    "te_attribute":colorScheme["typeerror"]+"Invalid Attribute!"+colorScheme["default"],
    "te_import_unspecified":colorScheme["typeerror"]+"No property specified!"+colorScheme["default"],
    "te_no_level":colorScheme["typeerror"]+"No level in memory!"+colorScheme["default"],
    "te_file_open_decline":colorScheme["typeerror"]+"No File Opened!"+colorScheme["default"],
    "te_file_save_decline":colorScheme["typeerror"]+"No Path Selected!"+colorScheme["default"],
    "te_file_busy":colorScheme["typeerror"]+"File in use!"+colorScheme["default"],
    "te_file_name":colorScheme["typeerror"]+"No such file or directory!"+colorScheme["default"],
    "te_file_type":colorScheme["typeerror"]+"Invalid file format!"+colorScheme["default"],
    "te_rep_no_attr":colorScheme["typeerror"]+"No data specified!"+colorScheme["default"],
    "te_rep_sublvl":colorScheme["typeerror"]+"Invalid sublevel!"+colorScheme["default"],
    "te_rep_smf_desc":colorScheme["typeerror"]+"No description attribute exists for SMF."+colorScheme["default"],
    "te_rep_smf_bg":colorScheme["typeerror"]+"No background attribute exists for SMF. Please specify whether you're modifying a level or bonus background."+colorScheme["default"],
    "te_rep_smf_mus":colorScheme["typeerror"]+"No music attribute exists for SMF. Please specify whether you're modifying the level or bonus music."+colorScheme["default"],
    "te_rep_smf_powerup":colorScheme["typeerror"]+"No start state attribute exists for SMF."+colorScheme["default"],
    "te_rep_smf_url":colorScheme["typeerror"]+"SMF has no custom backgrounds."+colorScheme["default"],
    "te_rep_smf_layer":colorScheme["typeerror"]+"SMF has no layers."+colorScheme["default"],
    "te_rep_smf2_width":colorScheme["typeerror"]+"Changing the level width in an SMF2 level without changing the level tiles will cause issues. Action denied."+colorScheme["default"],
    "te_rep_smf2_sublvl":colorScheme["typeerror"]+"SMF2 has no sublevel distinction."+colorScheme["default"],
    "te_rep_smf2_start":colorScheme["typeerror"]+"In SMF2, player's start coordinates are stored in entrance data, not the header."+colorScheme["default"],
    "success":colorScheme["success"]+"Success!"+colorScheme["default"],
    "greet_info":"Visit "+colorScheme["link"]+"https://github.com/AeroPurple/SMFLevelReader"+colorScheme["default"]+" to report issues and download updates!",
    "greet_intro":"First time? Type in "+colorScheme["command"]+"help"+colorScheme["default"]+" to get the list of commands, or type in "+colorScheme["command"]+"settings"+colorScheme["default"]+" to change how this program works.",
    "greet_ask":"What would you like to do?",
    "conf_ver_title":"Reported config version: ",
    "conf_ver_hi":"Unknown ",
    "conf_ver_inv":"Invalid ",
    "opt_conf_title_ms":"Title screen halt (ms): ",
    "opt_conf_title_pad":"Title padding style: ",
    "opt_conf_ansi":"Use ANSI escape codes: ",
    "opt_btn_reset":"Reset All",
    "opt_btn_cancel":"Cancel",
    "opt_btn_save":"Save",
    "title_s":"Settings",
    "title_r_h":"Header",
    "title_file_open_request":"Please open a Super Mario Flash level file.",
    "exit_s":"Exited settings page.",
    "exit_r_h":"Exited header editor.",
    "exit_input":"\nInput prompt cancelled.",
    "info_game":colorScheme["bold"]+"Game: "+colorScheme["default"],
    "info_smf":"Super Mario Flash",
    "info_smfe":"Super Mario Flash Ver. E",
    "info_smf2":"Super Mario Flash 2",
    "info_smf2c":"Super Mario Flash 2 Ver. C",
    "info_name":colorScheme["bold"]+"Level Name: "+colorScheme["default"],
    "info_start":colorScheme["bold"]+"Start Point: "+colorScheme["default"],
    "info_level_bg":colorScheme["bold"]+"Level Background: "+colorScheme["default"],
    "info_level_mus":colorScheme["bold"]+"Level Music: "+colorScheme["default"],
    "info_level_x":colorScheme["bold"]+"Level Width: "+colorScheme["default"],
    "info_level_warps":colorScheme["bold"]+"Level Warps:"+colorScheme["default"],
    "info_bonus_bg":colorScheme["bold"]+"Bonus Background: "+colorScheme["default"],
    "info_bonus_mus":colorScheme["bold"]+"Bonus Music: "+colorScheme["default"],
    "info_bonus_x":colorScheme["bold"]+"Bonus Width: "+colorScheme["default"],
    "info_no_anim":"No Animation",
    "info_gen_tx":" tiles horz, ",
    "info_gen_ty":" tiles vert",
    "gen_softlocker":colorScheme["warning"]+"softlocks the game"+colorScheme["default"],
    "gen_modify_to":"Change {0} to: ",
    "gen_modify_from_to":"Change {0} from "+colorScheme["bold"]+"{1}"+colorScheme["default"]+" to: ",
    "gen_modified_to":colorScheme["success"]+"Successfully changed {0} to {1}"+colorScheme["default"],
    "gen_modified_from_to":colorScheme["success"]+"Successfully changed {0} from {1} to {2}"+colorScheme["default"],
    "gen_inv":"invalid, ",
    "gen_none":"None",
    "gen_none_f":colorScheme["null"]+"None"+colorScheme["default"],
    "gen_no":"No",
    "gen_yes":"Yes",
    "q":"\""
}

smfe_background_names=[
    colorScheme["null"]+"None"+colorScheme["default"],
    "Land",
    "Cave",
    "Forest",
    "Castle",
    "Snow",
    "Ghost", # 6 - SMF Limit #
    "Hills",
    "Snow 2",
    "Rock",
    "Castle 2",
    "Ghost 2",
    "Cave 2",
    "Autumn",
    "Night",
    "Dark",
    "Night 2",
    "Land 2",
    "Waterfall",
    "Ruins",
    "Sky",
    "Mountain",
    "Snow 3",
    "Castle Walls",
    "Castle 3",
    "Castle 4",
    "Desert",
    "Volcano",
    "Volcanic Cave"
]

smfe_music_names=[
    colorScheme["null"]+"None"+colorScheme["default"],
    "Overworld",
    "Forest",
    "Athletic",
    "Map",
    "Underground",
    "Fortress",
    "Bowser",
    "Toad Shop/Level Builder",
    "Invincibile",
    "Level Complete",
    "World Complete", # 11 - SMF Limit #
    "Castle","Bonus",
    "Final Bowser",
    "Ghost House (SMW)",
    "Ghost House (SMB)",
    "Volcano",
    "Airship",
    "Desert"
]

smf2_background_names=[
    colorScheme["null"]+"None"+colorScheme["default"],
    "Clouds",
    "Hills",
    "Forest",
    "Ghost House",
    "Underground",
    "Underwater",
    "Castle",
    "Bonus",
    "Night",
    colorScheme["null"]+"None"+colorScheme["default"],
    colorScheme["null"]+"Custom"+colorScheme["default"]
]

smf2c_background_names=[
    colorScheme["null"]+"None"+colorScheme["default"],
    "Clouds (Color 2)",
    "Hills (Colors 1/1)",
    "Forest (Color 3)",
    "Ghost House (Color 1)",
    "Underground",
    "Underwater (Color 1)",
    "Castle (Color 1)",
    "Bonus (Color 1)",
    "Night (Color 1)",
    colorScheme["null"]+"None"+colorScheme["default"],
    colorScheme["null"]+"Custom"+colorScheme["default"],
    "Tall Hills (Color 4)",
    "Mountains (Colors 2/3)",
    "Forest (Color 4)",
    "Candle Castle (Color 1)",
    "Small Hills (Colors 1/5)",
    "Tall Mountains (Colors 3/1)",
    "Solid (Color 6)",
    "Clouds (Color 1)",
    "Clouds (Color 3)",
    "Clouds (Color 4)",
    "Clouds (Color 5)",
    "Hills (Colors 1/2)",
    "Hills (Colors 1/3)",
    "Hills (Colors 1/4)",
    "Hills (Colors 1/5)",
    "Hills (Colors 2/1)",
    "Hills (Colors 2/2)",
    "Hills (Colors 2/3)",
    "Hills (Colors 2/4)",
    "Hills (Colors 2/5)",
    "Hills (Colors 3/1)",
    "Hills (Colors 3/2)",
    "Hills (Colors 3/3)",
    "Hills (Colors 3/4)",
    "Hills (Colors 3/5)",
    "Hills (Colors 4/1)",
    "Hills (Colors 4/2)",
    "Hills (Colors 4/3)",
    "Hills (Colors 4/4)",
    "Hills (Colors 4/5)",
    "42" ########### Incomplete !!! ###########
]

smf2c_music_names=[
    colorScheme["null"]+"None"+colorScheme["default"],
    "Overworld",
    "Athletic",
    "Castle",
    "Underground",
    "Underwater",
    "Ghost House",
    "Airship",
    "Bonus",
    "Bowser",
    "Invincibile",
    "P-Switch",
    "Minor Fanfare",
    "Major Fanfare",
    "Player Down",
    "Boom Boom",
    "Plains Map",
    "Underworld Map",
    "Key Exit",
    colorScheme["null"]+"Custom"+colorScheme["default"]
]

smf2_powerup_names=[
    "Small Mario",
    "Big Mario",
    "Fire Mario",
    "Cape Mario",
    "Frictionless Cape Mario (unintended)",
    "Yoshi-Riding Small Mario (unintended, "+colorScheme["warning"]+"unstable"+colorScheme["default"]+")",
    "Yoshi-Riding Big Mario (unintended, "+colorScheme["warning"]+"unstable"+colorScheme["default"]+")",
    "Yoshi-Riding Fire Mario (unintended, "+colorScheme["warning"]+"unstable"+colorScheme["default"]+")",
    "Yoshi-Riding Cape Mario (unintended, "+colorScheme["warning"]+"unstable"+colorScheme["default"]+")",
    "Door-Entering Mario (unintended, "+colorScheme["warning"]+"crashes the game"+colorScheme["default"]+")",
    "Vine-Climbing Small Mario (unintended)",
    "Vine-Climbing Big Mario (unintended)",
    "Vine-Climbing Fire Mario (unintended)",
    "Vine-Climbing Cape Mario (unintended)",
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"],
    "Carrying Small Mario (unintended)",
    "Carrying Big Mario (unintended)",
    "Carrying Fire Mario (unintended)",
    "Carrying Cape Mario (unintended)",
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"],
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"],
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"],
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"],
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"],
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"],
    "Swimming Small Mario",
    "Swimming Big Mario",
    "Swimming Fire Mario",
    "Swimming Cape Mario",
    colorScheme["null"]+"No Mario (unintended)"+colorScheme["default"]
]

smf2_entrance_types=[
    "Standard Entrance",
    "Repeating Door Animation (unintended, "+colorScheme["warning"]+"softlocks the game"+colorScheme["default"]+")",
    "Upward Pipe Entrance",
    "Downward Pipe Entrance",
    "Repeating Downward Pipe Animation (unintended, "+colorScheme["warning"]+"softlocks the game"+colorScheme["default"]+")",
    "Repeating Upward Pipe Animation (unintended, "+colorScheme["warning"]+"softlocks the game"+colorScheme["default"]+")",
    "Pipe Entrance Right","Pipe Entrance Left",
    "Repeating Pipe Left Animation (unintended, "+colorScheme["warning"]+"softlocks the game"+colorScheme["default"]+")",
    "Repeating Pipe Right Animation (unintended, "+colorScheme["warning"]+"softlocks the game"+colorScheme["default"]+")",
    "No Mario (unintended, "+colorScheme["warning"]+"softlocks the game"+colorScheme["default"]+")"
]

smf2_entrance_powerups=[
    "No Mario (unintended, "+colorScheme["warning"]+"unstable"+colorScheme["default"]+")",
    "Facing Right",
    "Facing Left",
    "Running Right (unintended)",
    "Running Left (unintended)",
    "Skidding Right (unintended)",
    "Skidding Left (unintended)",
    "Jumping Right (unintended)",
    "Jumping Left (unintended)",
    "Falling Right (unintended)",
    "Falling Left (unintended)",
    "Crouching Right (unintended)",
    "Crouching Left (unintended)",
    "Sliding Right (unintended)",
    "Sliding Left (unintended)",
    "Kicking Right (unintended)",
    "Kicking Left (unintended)",
    "Superposition Mario (unintended)"
]

smf2_exit_types=[
    colorScheme["null"]+"None"+colorScheme["default"],
    "Door",
    "P-Switch Door",
    "Downward Pipe",
    "Upward Pipe",
    "Pipe Right",
    "Pipe Left"
]

smf_tiles=[
    ["·","Empty"],
    ["█","Land Top Center"],
    ["█","Brown Block"],
    ["█","Blue Block"],
    ["█","Forest Top Center"],
    ["█","Forest Center"],
    ["█","Invisible"],
    ["█","Empty Brown ?"],
    ["█","Spin"],
    ["█","Bowser Bridge"],
    ["█","Cave Top Center"],
    ["█","Brown Brick"],
    ["█","Blue Brick"],
    ["█","Castle Top Center"],
    ["█","Castle Center"],
    ["█","Invisible"],
    ["█","Grass Platform Center"],
    ["█","Grass Platform Left"],
    ["█","Grass Platform Right"],
    ["▒","Grass Platform Stem Single"],
    ["▒","Grass Platform Stem Left"],
    ["▒","Grass Platform Stem Center"],
    ["▒","Grass Platform Stem Right"],
    ["█","Green Pipe Vert Top Left"],
    ["█","Green Pipe Vert Top Right"],
    ["█","Green Pipe Vert Stem Left"],
    ["█","Green Pipe Vert Stem Right"],
    ["█","Stone Brick Single"],
    ["█","Stone Brick Right"],
    ["█","Stone Brick Left"],
    ["█","Castle Right"],
    ["█","Castle Left"],
    ["█","Castle Top Left"],
    ["█","Castle Top Right"],
    ["█","Castle Left and Up Join"],
    ["█","Castle Right and Up Join"],
    ["█","Snow Top Center"],
    ["█","Grey Pipe Vert Top Left"],
    ["█","Grey Pipe Vert Top Right"],
    ["█","Grey Pipe Vert Stem Left"],
    ["█","Grey Pipe Vert Stem Right"],
    ["█","Forest Right and Up Join"],
    ["█","Forest Right"],
    ["█","Forest Top Right"],
    ["█","Forest Top Left"],
    ["█","Forest Left and Up Join"],
    ["█","Forest Left"],
    ["█","Star ?"],
    ["█","Powerup ?"],
    ["█","Coin ?"],
    ["≈","Lava"],
    ["=","Up Platform"],
    ["=","Down Platform"],
    ["=","Side 2 Platform"],
    ["=","Side 1 Platform"],
    ["=","Fall Platform"],
    ["0","Coin"],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["×","Brown Goomba"],
    ["×","Blue Goomba"],
    ["×","Podoboo"],
    ["█","Bullet Bill Launcher Left"],
    ["×","Spiny"],
    ["×","Green Koopa Walking"],
    ["×","Hammer Bro"],
    ["×","Green Koopa Jumping"],
    ["█","Firebar"],
    ["×","Moving Piranha"],
    ["×","Lakitu"],
    ["×","Standing Piranha"],
    ["×","Green Koopa Flying"],
    ["█","Bullet Bill Launcher Right"],
    ["×","Red Koopa Walking"],
    ["×","Red Koopa Jumping"],
    ["×","Red Koopa Flying"],
    ["×","Buzzy Beetle"],
    ["×","Bowser"],
    ["×","Bullet Bill Left"],
    ["×","Bullet Bill Right"],
    ["×","Bowser Flame Right"],
    ["×","Bowser Flame Left"],
    ["█","Flagpole Blue Block"],
    ["█","Flagpole Brown Block"],
    ["×","Boo"],
    ["█","Green Pipe Horz Top Right"],
    ["█","Green Pipe Horz Bottom Right"],
    ["█","Green Pipe Vert Bottom Left"],
    ["█","Green Pipe Vert Bottom Right"],
    ["█","Green Pipe Horz Bottom Left"],
    ["█","Green Pipe Horz Top Left"],
    ["█","Green Pipe Horz Stem Bottom"],
    ["█","Green Pipe Horz Stem Top"],
    ["√","Win"],
    ["|","Flag Pole"],
    [">","Flag"],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["▒","Castle Base Left Top"],
    ["▒","Castle Base Left"],
    ["▒","Castle Base Top"],
    ["▒","Castle Base"],
    ["▒","Castle Door Bottom"],
    ["▒","Castle Base Right Top"],
    ["▒","Castle Base Right"],
    ["▒","Castle Roof Right Edge"],
    ["▒","Castle Roof Medium 5"],
    ["▒","Castle Roof Medium 4"],
    ["▒","Castle Roof Medium 3"],
    ["▒","Castle Roof Medium 2"],
    ["▒","Castle Roof Medium 1"],
    ["▒","Castle Roof Left Edge"],
    ["▒","Castle Window Right"],
    ["▒","Castle Door Top"],
    ["▒","Castle Window Left"],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["█","Land Top Left"],
    ["█","Land Top Right"],
    ["█","Castle Solid Brick"],
    ["█","Cave Top Left"],
    ["█","Cave Top Right"],
    ["█","Snow Top Left"],
    ["█","Snow Top Right"],
    ["▒","Mushroom Stem"],
    ["▒","Mushroom Stem Top"],
    ["█","Mushroom Platform Left"],
    ["█","Mushroom Platform Center"],
    ["█","Mushroom Platform Right"],
    ["█","Hidden Coin ?"],
    ["▒","Bush Left"],
    ["▒","Bush Center"],
    ["▒","Bush Right"],
    ["▒","Snowy Tree Top"],
    ["▒","Snowy Tree Bottom"],
    ["▒","Tree Top"],
    ["▒","Tree Bottom"],
    ["▒","Tree Stem"],
    ["▒","Snowy Tree Small"],
    ["▒","Tree Small"],
    ["▒","Snowy Fence"],
    ["▒","Fence"],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["S","Start Point Top"],
    ["S","Start Point Bottom"],
    ["↕","Door Top"],
    ["↕","Door Bottom"],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["↓","In Warp Down Left"],
    ["↓","In Warp Down Right"],
    ["→","In Warp Right Top"],
    ["→","In Warp Right Bottom"],
    ["←","In Warp Left Top"],
    ["←","In Warp Left Bottom"],
    ["↑","In Warp Up Left"],
    ["↑","In Warp Up Right"],
    ["↕","Castle Door Top"],
    ["↕","Castle Door Bottom"],
    ["↑","Out Warp Up Left"],
    ["↑","Out Warp Up Right"],
    ["←","Out Warp Left Top"],
    ["←","Out Warp Left Bottom"],
    ["→","Out Warp Right Top"],
    ["→","Out Warp Right Bottom"],
    ["↓","Out Warp Down Left"],
    ["↓","Out Warp Down Right"],
    ["O","Out Warp Appear Top"],
    ["O","Out Warp Appear Bottom"],
    ["█","Green Pipe Left and Up Join"],
    ["█","Green Pipe Left and Down Join"],
    ["█","Green Pipe Right and Up Join"],
    ["█","Green Pipe Right and Down Join"],
    ["█","Ghost Platform"],
    ["█","Ghost Pillar Top"],
    ["█","Ghost Pillar"],
    ["█","Ghost Block"],
    ["█","Ghost Bricks Left"],
    ["█","Ghost Bricks Right"],
    ["█","Grey Pipe Horz Bottom Left"],
    ["█","Grey Pipe Horz Top Left"],
    ["█","Grey Pipe Horz Stem Top"],
    ["█","Grey Pipe Horz Stem Bottom"],
    ["█","Grey Pipe Left and Up Join"],
    ["█","Grey Pipe Left and Down Join"],
    ["█","Grey Pipe Right and Up Join"],
    ["█","Grey Pipe Right and Down Join"],
    ["█","Grey Pipe Vert Bottom Left"],
    ["█","Grey Pipe Vert Bottom Right"],
    ["█","Grey Pipe Horz Top Left"],
    ["█","Grey Pipe Horz Bottom Left"],
    ["×","Dry Bones"],
    ["×","Thwomp"], # 194 - SMF tile limit #
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
]

smf2_tiles=[
    ["·","Empty"],
    ["█","Grey Rock"],
    ["═","Ground Top Center"],
    ["▒","Monty Mole Hole"],
    ["/","Ground 45° Slope Top Up"],
    ["╝","Ground Left and Up Join"],
    ["\\","Ground 45° Slope Top Down"],
    ["╚","Ground Right and Up Join"],
    ["/","Ground 22.5° Slope Top Up 1"],
    ["▒","Ground 22.5° Slope Top Up Extend 1"],
    ["/","Ground 22.5° Slope Top Up 2"],
    ["▒","Ground 22.5° Slope Top Up Extend 2"],
    ["▒","Ground Center"],
    ["\\","Ground 22.5° Slope Top Down 1"],
    ["▒","Ground 22.5° Slope Top Down Extend 1"],
    ["\\","Ground 22.5° Slope Top Down 2"],
    ["▒","Ground 22.5° Slope Top Down Extend 2"],
    ["/","Ground 11.25° Slope Top Up 1"],
    ["▒","Ground 11.25° Slope Top Up Extend 1"],
    ["/","Ground 11.25° Slope Top Up 2"],
    ["▒","Ground 11.25° Slope Top Up Extend 2"],
    ["/","Ground 11.25° Slope Top Up 3"],
    ["/","Ground 11.25° Slope Top Up 4"],
    ["\\","Ground 11.25° Slope Top Down 1"],
    ["▒","Ground 11.25° Slope Top Down Extend 1"],
    ["\\","Ground 11.25° Slope Top Down 2"],
    ["▒","Ground 11.25° Slope Top Down Extend 2"],
    ["\\","Ground 11.25° Slope Top Down 3"],
    ["\\","Ground 11.25° Slope Top Down 4"],
    ["/","Grey Underground 67.5° Slope Top Up 2"],
    ["/","Grey Underground 67.5° Slope Top Up 1"],
    ["▒","Grey Underground 67.5° Slope Top Up Extend"],
    ["\\","Grey Underground 67.5° Slope Top Down 2"],
    ["\\","Grey Underground 67.5° Slope Top Down 1"],
    ["▒","Grey Underground 67.5° Slope Top Down Extend"],
    ["≈","Opaque Water"],
    ["Y","Vine"],
    ["/","Pink Diagonal Right"],
    ["╒","Ground Top Left Semisolid"],
    ["\\","Pink Diagonal Left"],
    ["│","Ground Left Semisolid"],
    ["/","Grey Underground 45° Slope Bottom Up"],
    ["/","Grey Underground 45° Slope Bottom Up Extend"],
    ["\\","Grey Underground 45° Slope Bottom Down"],
    ["\\","Grey Underground 45° Slope Bottom Down Extend"],
    ["/","Grey Underground 22.5° Slope Bottom Up 2"],
    ["/",colorScheme["null"]+"Null"+colorScheme["default"]], # 46 - teleports player downwards from left and right, and kills from top and bottom. May be a slope.
    ["/","Grey Underground 22.5° Slope Bottom Up 1"],
    ["/","Grey Underground 22.5° Slope Bottom Up Extend"],
    ["\\","Grey Underground 22.5° Slope Bottom Down 2"],
    ["\\",colorScheme["null"]+"Null"+colorScheme["default"]], # 50 - teleports player downwards from left and right, and kills from top and bottom. May be a slope.
    ["\\","Grey Underground 22.5° Slope Bottom Down 1"],
    ["\\","Grey Underground 22.5° Slope Bottom Down Extend"],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
    ["█","Flip Block"],
    ["█","Coin ?"],
    ["█","Mushroom ?"],
    ["█","Flower ?"],
    ["█","Feather ?"],
    ["█","Star ?"],
    ["█","Yoshi ?"],
    ["█","Green !"],
    ["█","Yellow !"],
    ["█","Red !"],
    ["█","Blue !"],
    ["█","Disabled Flip Block"],
    ["█","Message Block"],
    ["█","Vine Flip Block"],
    ["║","Ground Left"],
    ["╗","Ground Top Right"],
    ["╚","Ground Right and Up Join"],
    ["╕","Ground Top Right Semisolid"],
    ["│","Ground Right Semisolid"],
    ["║","Ground Right"],
    ["\\","Ground 45° Slope Bottom Down Non-Solid"],
    ["\\","Ground 45° Slope Bottom Down Non-Solid and Top Up Join"],
    ["/","Ground 45° Slope Top Up"],
    ["\\","Ground 45° Slope Top Down Non-Solid and Top Up Join"],
    ["\\","Ground 45° Slope Top Down Non-Solid"],
    ["╔","Grey Underground Top Left"],
    ["═","Grey Underground Top Center"],
    ["▒","Grey Underground Center"],
    ["║","Grey Underground Left"],
    ["╒","Grey Underground Top Left Semisolid"],
    ["│","Grey Underground Left Semisolid"],
    ["╗","Grey Underground Top Right"],
    ["═","Grey Underground Bottom Center"],
    ["║","Grey Underground Right"],
    ["╕","Grey Underground Top Right Semisolid"],
    ["│","Grey Underground Right Semisolid"],
    ["╚","Grey Underground Right and Up Join"],
    ["╝","Grey Underground Left and Up Join"],
    ["/","Grey Underground 45° Slope Top Up"],
    ["╝","Grey Underground Left and Up Join"],
    ["/","Grey Underground 22.5° Slope Top Up 1"],
    ["▒","Grey Underground 22.5° Slope Top Up Extend 1"],
    ["/","Grey Underground 22.5° Slope Top Up 2"],
    ["▒","Grey Underground 22.5° Slope Top Up Extend 2"],
    ["/","Grey Underground 11.25° Slope Top Up 1"],
    ["▒","Grey Underground 11.25° Slope Top Up Extend 1"],
    ["/","Grey Underground 11.25° Slope Top Up 2"],
    ["▒","Grey Underground 11.25° Slope Top Up Extend 2"],
    ["/","Grey Underground 11.25° Slope Top Up 3"],
    ["/","Grey Underground 11.25° Slope Top Up 4"],
    ["\\","Grey Underground 45° Slope Top Down"],
    ["╚","Grey Underground Right and Up Join"],
    ["\\","Grey Underground 22.5° Slope Top Down 1"],
    ["▒","Grey Underground 22.5° Slope Top Down Extend 1"],
    ["\\","Grey Underground 22.5° Slope Top Down 2"],
    ["▒","Grey Underground 22.5° Slope Top Down Extend 2"],
    ["\\","Grey Underground 11.25° Slope Top Down 1"],
    ["▒","Grey Underground 11.25° Slope Top Down Extend 1"],
    ["\\","Grey Underground 11.25° Slope Top Down 2"],
    ["▒","Grey Underground 11.25° Slope Top Down Extend 2"],
    ["\\","Grey Underground 11.25° Slope Top Down 3"],
    ["\\","Grey Underground 11.25° Slope Top Down 4"],
    ["═","Rope Platform"],
    ["▒","Mushroom Stem Single"],
    ["╔","Castle Top Left"],
    ["═","Castle Top Center"],
    ["▒","Castle Center"],
    ["║","Castle Left"],
    ["╝","Castle Left and Up Join"],
    ["╒","Castle Top Left Semisolid"],
    ["│","Castle Left Semisolid"],
    ["╔","Castle Stone Top Left"],
    ["═","Castle Stone Top Center"],
    ["║","Castle Stone Left"],
    ["█","Castle Stone Center"],
    ["╚","Castle Stone Bottom Left"],
    ["═","Castle Stone Bottom Center"],
    ["╗","Castle Stone Top Right"],
    ["║","Castle Stone Right"],
    ["╝","Castle Stone Bottom Right"],
    ["╗","Castle Top Right"],
    ["║","Castle Right"],
    ["╚","Castle Right and Up Join"],
    ["╕","Castle Top Right Semisolid"],
    ["│","Castle Right Semisolid"],
    ["█","Ghost Wood"],
    ["M","Ghost Spikes"],
    ["\\","Ghost Stairs Down"],
    ["▒","Ghost Stairs Down Extend"],
    ["▒","Ghost Stem"],
    ["▒","Ghost Stem Top"],
    ["═","Ghost Platform"],
    ["╔","Ghost Box Top Left"],
    ["╠","Ghost Box Left and Horz Join"],
    ["═","Ghost Box Top"],
    ["║","Ghost Box Left"],
    ["═","Ghost Box Horz"],
    ["█","Ghost Box Center"],
    ["╗","Ghost Box Top Right"],
    ["╣","Ghost Box Right and Horz Join"],
    ["║","Ghost Box Right"],
    ["═","Ghost Box Bottom"],
    ["█","Ghost Bricks Left"],
    ["█","Ghost Bricks Right"],
    ["╚","Ghost Box Bottom Left"],
    ["╝","Ghost Box Bottom Right"],
    ["/","Ghost Stairs Up"],
    ["▒","Ghost Stairs Up Extend"],
    ["▒","Ghost Bricks Background"],
    ["╒","Mushroom Platform Left"],
    ["═","Mushroom Platform Center"],
    ["╕","Mushroom Platform Right"],
    ["│","Mushroom Stem Left"],
    ["▒","Mushroom Stem Center"],
    ["│","Mushroom Stem Right"],
    ["═","Bonus Bottom"],
    ["║","Bonus Right"],
    ["║","Bonus Left"],
    ["═","Bonus Top Center"],
    ["█","Bonus Center"],
    ["╝","Bonus Bottom Right"],
    ["═","Wooden Bridge"],
    ["▒","Wooden Bridge Extend"],
    ["╔","Yellow Underground Top Left"],
    ["═","Yellow Underground Top Center"],
    ["║","Yellow Underground Left"],
    ["╗","Yellow Underground Top Right"],
    ["║","Yellow Underground Right"],
    ["╝","Yellow Underground Left and Up Join"],
    ["╚","Yellow Underground Right and Up Join"],
    ["/","Yellow Underground 45° Slope Top Up"],
    ["╝","Yellow Underground Left and Up Join"],
    ["/","Yellow Underground 22.5° Slope Top Up 1"],
    ["▒","Yellow Underground 22.5° Slope Top Up Extend 1"],
    ["/","Yellow Underground 22.5° Slope Top Up 2"],
    ["▒","Yellow Underground 22.5° Slope Top Up Extend 2"],
    ["\\","Yellow Underground 45° Slope Top Down"],
    ["╚","Yellow Underground Right and Up Join"],
    ["\\","Yellow Underground 22.5° Slope Top Down 1"],
    ["▒","Yellow Underground 22.5° Slope Top Down Extend 1"],
    ["\\","Yellow Underground 22.5° Slope Top Down 2"],
    ["▒","Yellow Underground 22.5° Slope Top Down Extend 2"],
    ["\\","Yellow Underground 45° Slope Bottom Down"],
    ["╗","Yellow Underground Left and Down Join"],
    ["\\","Yellow Underground 22.5° Slope Bottom Down 1"],
    ["▒","Yellow Underground 22.5° Slope Bottom Down Extend 1"],
    ["\\","Yellow Underground 22.5° Slope Bottom Down 2"],
    ["▒","Yellow Underground 22.5° Slope Bottom Down Extend 2"],
    ["/","Yellow Underground 45° Slope Bottom Up"],
    ["╔","Yellow Underground Right and Down Join"],
    ["/","Yellow Underground 22.5° Slope Bottom Up 1"],
    ["▒","Yellow Underground 22.5° Slope Bottom Up Extend 1"],
    ["/","Yellow Underground 22.5° Slope Bottom Up 2"],
    ["▒","Yellow Underground 22.5° Slope Bottom Up Extend 2"],
    ["▒","Yellow Underground Center"],
    ["≈","Opaque Water Top"],
    ["█","Brown Block"],
    ["═","Cloud"],
    ["═","Yellow Bridge"],
    ["▒","Yellow Bridge Extend"],
    ["█","Yellow Small Pipe Left"],
    ["█","Yellow Pipe Center"],
    ["█","Yellow Pipe Right"],
    ["█","Green Small Pipe Top"],
    ["█","Green Small Pipe Center"],
    ["█","Green Small Pipe Bottom"],
    ["╔","Green Pipe Vert Top Left"],
    ["╗","Green Pipe Vert Top Right"],
    ["║","Green Pipe Vert Stem Left"],
    ["║","Green Pipe Vert Stem Right"],
    ["╚","Green Pipe Vert Bottom Left"],
    ["╝","Green Pipe Vert Bottom Right"],
    ["╔","Green Pipe Horz Top Left"],
    ["╚","Green Pipe Horz Bottom Left"],
    ["═","Green Pipe Horz Stem Top"],
    ["═","Green Pipe Horz Stem Bottom"],
    ["╗","Green Pipe Horz Top Right"],
    ["╝","Green Pipe Horz Bottom Right"],
    ["╔","Yellow Pipe Vert Top Left"],
    ["╗","Yellow Pipe Vert Top Right"],
    ["║","Yellow Pipe Vert Stem Left"],
    ["║","Yellow Pipe Vert Stem Right"],
    ["═","Yellow Underground Bottom Center"],
    ["█","Ghost Ground Top Center"],
    ["▒","Goal Pole Top"],
    ["▒","Goal Pole"],
    ["0","Coin"],
    ["╔","Ground Top Left"],
    ["╝","Ground Left and Up Join"],
    ["≈","Seethrough Water Top"],
    ["≈","Seethrough Water"],
    ["≈","Lava Top"],
    ["≈","Lava"],
    ["↕","Door"],
    ["↕","P-Switch Door"],
    ["ʌ","Castle Spike Up"],
    ["v","Castle Spike Down"],
    ["<","Castle Spike Left"],
    [">","Castle Spike Right"],
    ["▒","Dotted Green !"],
    ["▒","Dotted Yellow !"],
    ["▒","Dotted Red !"],
    ["▒","Dotted Blue !"],
    ["▒","Checkpoint Pole Light Top"],
    ["▒","Checkpoint Pole Light"],
    ["▒","Checkpoint Pole Top"],
    ["▒","Checkpoint Pole"],
    ["▒","Bush Left"],
    ["▒","Bush Center"],
    ["▒","Bush Right"],
    ["/","Sloped Green Pipe Top Up Edge"], # The first word refers to the pipe tile's direction, i.e. ceiling/floor
    ["/","Sloped Green Pipe Top Up"],      # The second word specifies which way the tile is sloped, going to the right
    ["▒","Sloped Green Pipe Top Up Extend"], # Extend means that it is a tile that bridges the gap between a center
    ["▒","Sloped Green Pipe Center"],      # tile and a ceiling/floor. It is placed above or below the tile
    ["/","Sloped Green Pipe Bottom Up"],   # Edge refers to a corner
    ["▒","Sloped Green Pipe Bottom Up Extend"],
    ["▒","Sloped Green Pipe Top Up Edge Extend"],
    ["▒","Sloped Green Pipe Bottom Up Edge Extend"],
    ["▒","Sloped Green Pipe Top Down Extend"],
    ["\\","Sloped Green Pipe Top Down Left"],
    ["\\","Sloped Green Pipe Top Down Right"],
    ["/","Sloped Green Pipe Bottom Up Edge"],
    ["█","Tank Tires Left"],
    ["█","Tank Tires Center"],
    ["█","Tank Tires Right"],
    ["█","Tank Wood Center 1"],
    ["Z","Tank Wood Left Edge Chipped With Platform"],
    ["█","Tank Wood Window"],
    ["[","Tank Wood Left Edge"],
    ["]","Tank Wood Right Edge"],
    ["█","Tank Wood Center 2"],
    ["\\","Tank Wood Left Edge Chipped Long 1"],
    ["\\","Tank Wood Left Edge Chipped Long 2"],
    ["/","Tank Wood Right Edge Chipped"],
    ["\\","Tank Wood Left Edge Chipped"],
    ["█","Bullet Bill Launcher Stem Top"],
    ["█","Bullet Bill Launcher Stem"],
    ["╔","Torpedo Ted Launcher Top Left"],
    ["╗","Torpedo Ted Launcher Top Right"],
    ["╚","Torpedo Ted Launcher Bottom Left"],
    ["╝","Torpedo Ted Launcher Bottom Right"],
    ["╝","Grey Underground Bottom Right"],
    ["╚","Grey Underground Bottom Left"],
    ["╝","Yellow Underground Bottom Right"],
    ["╚","Yellow Underground Bottom Left"],
    ["×","Yoshi"],
    ["×","Red Koopa Shell"],
    ["█","Triple Platform"],
    ["×","Mushroom"],
    ["×","Fire Flower"],
    ["×","Feather"],
    ["×","Star"],
    ["×","Green Koopa Shell"],
    ["×","Green Koopa"],
    ["×","Red Koopa"],
    ["×","Key"],
    ["×","Goomba"],
    ["×","Shellless Green Koopa"],
    ["×","Shellless Red Koopa"],
    ["×","Jumping Green Koopa"],
    ["×","Jumping Red Koopa"],
    ["×","Flying Green Koopa"],
    ["×","Flying Red Koopa"],
    ["×","Monty Mole"],
    ["×","Monty Mole Out 1 Background"],
    ["×","Monty Mole Out 2 Ground"],
    ["×","Chargin' Chuck"],
    ["×","Jumpin'/Clappin' Chuck"],
    ["×","Baseball/Football Chuck"],
    ["×","Piranha Plant 1 Jump"],
    ["×","Piranha Plant 2 Jump Fire"],
    ["×","Super Koopa 1 Walk"],
    ["×","Walk/Slide Blue Koopa"],
    ["×","Buzzy Beetle Shell"],
    ["×","Buzzy Beetle"],
    ["×","Piranha Plant 3 Attached Upside-Down"],
    ["×","Swooper"],
    ["×","Volcano Lotus"],
    ["×","Yoshi Egg"],
    ["×","Spike Top"],
    ["×","Rex"],
    ["×","Spiny"],
    ["×","Super Koopa 2 Fly"],
    ["×","Bullet Bill"],
    ["×","Boo"],
    ["×","Boo Clock"],
    ["×","Boo Trail"],
    ["×","Eerie"],
    ["×","Dry Bones"],
    ["×","Bony Beetle"],
    ["█","Chain Ball"],
    ["×","Podoboo"],
    ["×","Thwimp"],
    ["×","Fuzzy/Lil' Sparky"],
    ["×","Thwomp"],
    ["×","Cheep Cheep Type 1 Horz/Vert"],
    ["×","Blurp"],
    ["×","Urchin Horz/Vert"],
    ["×","Wall Urchin"],
    ["×","Rip Van Fish"], # 354 - sleeping fish
    ["×","Fish Bone"],
    ["█","Single Rotating Platform"],
    ["=","Moving Platform"],
    ["=","Falling Platform"],
    ["█","Long Platform"],
    ["=","Floating Platform"],
    ["×","Springboard"],
    ["=","Hammer Bro Platform"],
    ["×","Pipe Lakitu"],
    ["×","Cloud Lakitu"],
    ["×","Big Boo/Banzai Bill"],
    ["×","Spikeball/Porcupuffer"],
    ["×","Mega Mole"],
    ["×","Saw"],
    ["×","Torpedo Ted Hand"],
    ["H","Goal Point 1 Gate"],
    ["S","Special Tile"],
    ["×","P-Switch"],
    ["↕","P-Switch Door"],
    ["×","! Switch"],
    ["H","Checkpoint"],
    ["×","Keyhole"],
    ["█","Bullet Bill Launcher"],
    ["G","Sprite Generator Bullet Bill/Super Koopa/Cheep Cheep"],
    ["×","Cheep Cheep Type 2 Jump"],
    ["A","Autoscroll 1/2/3"],
    ["√","Goal Point 2 Ball"],
    ["×","Boom Boom"],
    ["×","Bowser"],
    ["A","Autoscroll 4/5/6"],
    ["█","Brick Block"],
    ["█","Coin Brick"],
    ["█","Mushroom Brick"],
    ["█","Flower Brick"],
    ["█","Feather Brick"],
    ["█","Star Brick"],
    ["█","Yoshi Brick"],
    ["█","Vine Brick"],
    ["V","Muncher"],
    ["┌","Climbing Net Top Left"],
    ["┐","Climbing Net Top Right"],
    ["└","Climbing Net Bottom Left"],
    ["┘","Climbing Net Bottom Right"],
    ["─","Climbing Net Top Center"],
    ["─","Climbing Net Bottom Center"],
    ["│","Climbing Net Left"],
    ["│","Climbing Net Right"],
    ["X","Climbing Net Center"],
    ["┐","Climbing Net Left and Down Join"],
    ["┌","Climbing Net Right and Down Join"],
    ["┘","Climbing Net Left and Up Join"],
    ["└","Climbing Net Right and Up Join"], # 406 - SMF2 tile limit #
    ["·",colorScheme["null"]+"Null"+colorScheme["default"]],
]